### PR TITLE
Fix failure when target period is DJF

### PR DESCRIPTION
**Pull request by aaron-kaplan**
CPT allows dates to be expressed as either YYYY-MM or YYYY-MM-DD. In CPT seasonal target periods were intended to be expressed using YYYY-MM format, but pycpt currently uses YYYY-MM-DD for both seasonal and subseasonal. That works in most cases, but fails when the season ends in February, because in that case the season length in days is different in leap years than in non-leap years, which CPT rejects. Here we work around that by changing to YYYY-MM format for seasonal target periods.

This PR looks huge, but the substantive changes aren't that big. The first four commits do nothing but break up long lines to make the code more readable, and factor out some code that had been copy-pasted several times. Only the last two commits change the behavior. So I recommend reading one commit at a time, and concentrating on the last two.

With this change, the pycpt-operational-WAfrica notebook runs to completion. You may have to use `force_downloads = True` if you have files downloaded with the old version.

### CODE REVIEW

**Comment by jturmelle** [comment]
At first look, a question:

utilities/verify:is_valid_cptv10 almost duplicates fileio/cpt:is_valid_cpt10.  Is there a reason this function is defined twice and is slightly different?

Not part of your PR, but I think this is a bug.  My PyCharm IDE flagged it...
cpt.py: line 612 I think 
   `temp = da.isel({T: i}).values` 
should be 
    `temp = da.isel({T: j}).values`

because i hasn't been set at this point.

**Comment by jturmelle** [comment]
On Line 253 of cpt.py it looks like ndims is being used before it's defined.  ndims is defined within the if statement, but not the else statement.

**Review by jturmelle — APPROVED** [review]
I painstakingly went through all the lines and am pretty sure all the formatting changes are OK and didn't change any functionality.

The format_date_range looks appropriate as far as I can tell, and the February check is definitely right.

I approve this pull request, but I think the bugs I noticed in my previous comments should be addressed, if not in this pull request, then in a separate one.

**Comment by aaron-kaplan** [comment]
@jturmelle thanks. I'm putting it on my todo list to run a linter and fix the errors it flags. Regarding linne 612 I think it's actually supposed to be `{C: j}`.

**Comment by aaron-kaplan** [comment]
I pushed another commit that replaces individual email addresses with pycpt-help@iri, and fixes some more references to Kyle's individual github repo.

**Review by awrobertson — APPROVED** [review]
I tested it for DJF 2021-22 from Nov start and it worked :)

**Pull request merged**
